-- Script para criação da tabela de usuários com todos os campos necessários

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    nome VARCHAR(255),
    foto VARCHAR(255),              -- URL da foto principal que aparece no perfil
    fotos JSONB DEFAULT '[]'::jsonb, -- Array com URLs de todas as fotos (até 3)
    bio TEXT DEFAULT '',
    interesses JSONB DEFAULT '[]'::jsonb,
    venda1 BOOLEAN NOT NULL DEFAULT FALSE,
    venda2 BOOLEAN NOT NULL DEFAULT FALSE,
    idmatch JSONB DEFAULT '[]'::jsonb,
    reset_token VARCHAR(255),       -- Token para redefinição de senha
    reset_token_expires TIMESTAMP WITH TIME ZONE, -- Data de expiração do token
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Criação de índice para buscas por email
CREATE INDEX idx_usuarios_email ON usuarios(email);

-- Adicionar comentários para documentação
COMMENT ON TABLE usuarios IS 'Tabela de usuários do aplicativo Minha Coroa';
COMMENT ON COLUMN usuarios.id IS 'ID único do usuário';
COMMENT ON COLUMN usuarios.email IS 'Email do usuário (único)';
COMMENT ON COLUMN usuarios.senha IS 'Senha do usuário (hash)';
COMMENT ON COLUMN usuarios.nome IS 'Nome do usuário';
COMMENT ON COLUMN usuarios.foto IS 'URL da foto principal do perfil (imagem de avatar)';
COMMENT ON COLUMN usuarios.fotos IS 'Array de URLs com todas as fotos do usuário (até 3)';
COMMENT ON COLUMN usuarios.bio IS 'Descrição biográfica do usuário';
COMMENT ON COLUMN usuarios.interesses IS 'Array com interesses/hobbies do usuário';
COMMENT ON COLUMN usuarios.venda1 IS 'Flag indicando se o usuário adquiriu o plano Silver';
COMMENT ON COLUMN usuarios.venda2 IS 'Flag indicando se o usuário adquiriu o plano Gold';
COMMENT ON COLUMN usuarios.idmatch IS 'Array de IDs de usuários que deram match';
COMMENT ON COLUMN usuarios.reset_token IS 'Token único para redefinição de senha';
COMMENT ON COLUMN usuarios.reset_token_expires IS 'Data de expiração do token de redefinição de senha';
COMMENT ON COLUMN usuarios.created_at IS 'Data de criação do registro';

-- Para migração em tabelas existentes, execute:
-- 
-- ALTER TABLE usuarios ADD COLUMN bio TEXT DEFAULT '' NOT NULL;
-- ALTER TABLE usuarios ADD COLUMN interesses JSONB DEFAULT '[]'::jsonb NOT NULL;
-- ALTER TABLE usuarios ADD COLUMN fotos JSONB DEFAULT '[]'::jsonb NOT NULL;
-- ALTER TABLE usuarios ADD COLUMN reset_token VARCHAR(255);
-- ALTER TABLE usuarios ADD COLUMN reset_token_expires TIMESTAMP WITH TIME ZONE;
-- 
-- COMMENT ON COLUMN usuarios.foto IS 'URL da foto principal do perfil (imagem de avatar)';
-- COMMENT ON COLUMN usuarios.fotos IS 'Array de URLs com todas as fotos do usuário (até 3)';
-- COMMENT ON COLUMN usuarios.bio IS 'Descrição biográfica do usuário';
-- COMMENT ON COLUMN usuarios.interesses IS 'Array com interesses/hobbies do usuário';
-- COMMENT ON COLUMN usuarios.reset_token IS 'Token único para redefinição de senha';
-- COMMENT ON COLUMN usuarios.reset_token_expires IS 'Data de expiração do token de redefinição de senha';